/**
 * Encore Features tab searchable-settings entries.
 *
 * Part of the searchableSettings.ts domain-file split, mirroring the
 * settingsStore.ts / settingsMetadata.ts slice decomposition (see
 * settingsAnnotatorSlice.ts for that pattern).
 */

import type { SearchableSetting } from './searchableSettings';

export const ENCORE_SETTINGS: SearchableSetting[] = [
	{
		id: 'encore-usage-stats',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Usage & Stats',
		description:
			'Track queries, Auto Run sessions, coding activity, and view the Usage Dashboard with a configurable lookback window',
		keywords: [
			'usage',
			'stats',
			'analytics',
			'dashboard',
			'tracking',
			'wakatime',
			'lookback',
			'activity',
			'query',
			'coding',
			'metrics',
			'tokens',
			'cost',
		],
	},
	{
		id: 'encore-symphony',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Maestro Symphony',
		description:
			'Contribute to open source projects through curated repositories and playbook registries',
		keywords: [
			'symphony',
			'open source',
			'oss',
			'contribute',
			'repository',
			'registry',
			'registry sources',
			'sources',
			'playbook',
			'curated',
		],
	},
	{
		id: 'encore-cue',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Maestro Cue',
		description:
			'Event-driven automation (Beta) - trigger agent prompts on timers, file changes, agent completions, GitHub PRs/issues, and pending tasks',
		keywords: [
			'cue',
			'automation',
			'trigger',
			'event',
			'timer',
			'file watch',
			'watcher',
			'pipeline',
			'global cue settings',
			'global settings',
			'subscription',
			'github',
			'pr',
			'issue',
			'beta',
			'cron',
			'schedule',
		],
	},
	{
		id: 'encore-coworking',
		tab: 'encore',
		tabLabel: 'Encore Features',
		label: 'Coworking',
		description:
			'Beta - let agents read terminal scrollback on demand. Installs a per-agent MCP server (Claude Code, Codex, OpenCode, Factory Droid) and adds a `term:N` pill to terminal tabs.',
		keywords: [
			'coworking',
			'mcp',
			'terminal',
			'scrollback',
			'agent',
			'tools',
			'claude code',
			'codex',
			'opencode',
			'factory droid',
			'beta',
			'install',
			'server',
		],
	},
	{
		id: 'coworking-background-browsers',
		tab: 'encore',
		tabLabel: 'Encore Features',
		label: 'Coworking background browsing',
		description:
			'Let agents read and drive their own browser tabs while you are focused on a different agent. Keeps hidden webviews alive off-screen, LRU-capped (1-10).',
		keywords: [
			'coworking',
			'background',
			'browser',
			'browsing',
			'webview',
			'hidden',
			'cross-session',
			'lru',
			'limit',
		],
	},
	{
		id: 'encore-director-notes',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: "Director's Notes",
		description: 'Unified history view and AI-generated synopsis across all sessions (Beta)',
		keywords: [
			'director',
			'notes',
			'synopsis',
			'synopsis provider',
			'provider',
			'history',
			'summary',
			'lookback',
			'beta',
			'fleet',
			'unified',
		],
	},
	{
		id: 'encore-director-notes-default-mode',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: "Director's Notes Default Reading Mode",
		description:
			'Whether the AI Overview opens in Rich (widget dashboard) or Plain (markdown) mode',
		keywords: [
			'director',
			'notes',
			'rich',
			'plain',
			'mode',
			'reading',
			'default',
			'dashboard',
			'widgets',
			'markdown',
		],
	},
	{
		id: 'encore-director-notes-ideal-end-state',
		tab: 'encore',
		tabLabel: 'Encore Features',
		label: "Ideal End State (Director's Notes)",
		description:
			'Describe the projects in flight and what done looks like; notes prioritize them and add a progress section',
		keywords: [
			'ideal',
			'end state',
			'goal',
			'target',
			'objective',
			'progress',
			'director',
			'notes',
			'projects',
			'roadmap',
		],
	},
	{
		id: 'encore-pianola',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Pianola',
		description:
			'Autonomous manager agent (Beta). Watches your agents, auto-answers low-risk prompts from your rules, and escalates uncertain or high-risk ones. Can send messages to agents on your behalf',
		keywords: [
			'pianola',
			'autonomous',
			'manager',
			'agent',
			'watch',
			'auto-answer',
			'auto answer',
			'escalate',
			'rules',
			'supervise',
			'orchestrate',
			'beta',
		],
	},
	{
		id: 'encore-concerto',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Concerto',
		description:
			'Agent-composed native views. Agents build rich, app-styled data panels (Movements) and small always-on-top cards (Cadenzas) from a fixed block vocabulary, instead of plain chat text',
		keywords: [
			'concerto',
			'movement',
			'cadenza',
			'agent views',
			'views',
			'panel',
			'dashboard',
			'hud',
			'blockview',
			'data view',
			'visualize',
		],
	},
	{
		id: 'encore-groups-plus',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Groups+',
		description:
			'Nested group folders with standard icons and label colors. Turn it on to organize the sidebar without changing stored group data.',
		keywords: [
			'groups',
			'groups plus',
			'folder',
			'nested',
			'hierarchy',
			'icon',
			'color',
			'sidebar',
			'organization',
		],
	},
	{
		id: 'encore-a-cappella',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'A Cappella',
		description:
			'Voice interface (Beta). Speak a request, have it routed to the right agent and tab, and hear the reply read back. Enabling it only makes Voice Setup reachable; no microphone is opened until you start a session',
		keywords: [
			'a cappella',
			'acappella',
			'voice',
			'speech',
			'speak',
			'talk',
			'microphone',
			'mic',
			'dictation',
			'transcribe',
			'stt',
			'tts',
			'text to speech',
			'speech to text',
			'wake word',
			'hands free',
		],
	},
	{
		id: 'encore-a-cappella-voice-setup',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Voice Setup',
		description:
			'Pick where speech recognition, speech synthesis, and routing run, and download the local models. Nothing is downloaded until you press Download; every model is listed with its exact size, license, and install path',
		keywords: [
			'voice setup',
			'a cappella',
			'model',
			'models',
			'download',
			'local',
			'cloud',
			'whisper',
			'kokoro',
			'qwen',
			'bill of materials',
			'license',
			'install path',
			'offline',
		],
	},
	{
		id: 'encore-a-cappella-download-set',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Download voice models',
		description:
			'One button that downloads everything the current slot choices need. The size shown is the total of what is still missing, computed from the catalog',
		keywords: ['download', 'voice models', 'hands-free', 'fully local', 'set', 'bundle'],
	},
	{
		id: 'encore-a-cappella-stt',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Speech-to-Text',
		description:
			'Where your speech is transcribed. Local keeps every sample of your voice on this machine; cloud sends audio to a service you configure',
		keywords: [
			'speech to text',
			'stt',
			'transcribe',
			'transcription',
			'whisper',
			'dictation',
			'microphone',
		],
	},
	{
		id: 'encore-a-cappella-tts',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Text-to-Speech',
		description:
			'Where replies are spoken from. Local synthesises on this machine; cloud streams audio back from a service you configure',
		keywords: ['text to speech', 'tts', 'speak', 'voice', 'kokoro', 'synthesis', 'read aloud'],
	},
	{
		id: 'encore-a-cappella-brain',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Conductor Brain',
		description:
			'What decides which agent you meant. Local runs a small model here; cloud uses an API model, which is faster to set up and costs per request',
		keywords: ['conductor brain', 'brain', 'routing', 'route', 'qwen', 'llm', 'model'],
	},
	{
		id: 'encore-a-cappella-wake-word',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Wake word',
		description:
			'The always-on listener for the wake and stop words. Always local and always required for hands-free; there is no cloud option, by design',
		keywords: ['wake word', 'stop word', 'hands free', 'always on', 'openwakeword', 'hey maestro'],
	},
	{
		id: 'encore-a-cappella-agent-wake-phrases',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Per-agent phrases',
		description:
			'Give an agent its own wake phrase so saying it opens a session bound straight to that agent, with no routing step in between',
		keywords: [
			'per agent phrase',
			'agent wake phrase',
			'wake phrase',
			'agent phrase',
			'phrase',
			'per-agent',
		],
	},
	{
		id: 'encore-a-cappella-stop-word',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Stop word',
		description:
			'Ends the session: speech stops, the microphone closes, and Maestro goes back to waiting for the wake word. Not the same as interrupting a reply',
		keywords: [
			'stop word',
			'stop phrase',
			'nevermind',
			'shut up',
			'be quiet',
			'end session',
			'barge in',
			'interrupt',
		],
	},
	{
		id: 'encore-a-cappella-voice-hotkeys',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Voice hotkeys',
		description:
			'System-wide keys for talking to the Conductor without stealing focus, and for summoning Maestro to talk to the agent you are looking at',
		keywords: [
			'voice hotkey',
			'hotkey',
			'global hotkey',
			'push to talk',
			'talk to maestro',
			'talk to current agent',
			'shortcut',
			'keyboard',
		],
	},
	{
		id: 'encore-a-cappella-floor-timing',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Voice timing',
		description:
			'How long a key press has to be before it counts as holding the key, and how long an untouched microphone stays open',
		keywords: [
			'hold threshold',
			'tap vs hold',
			'push to talk',
			'idle timeout',
			'microphone timeout',
			'timing',
		],
	},
	{
		id: 'encore-a-cappella-models',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Models on disk',
		description:
			'What A Cappella is holding on disk: size, install date, last verified date, plus Remove and Re-verify for each model',
		keywords: [
			'models',
			'disk',
			'storage',
			'footprint',
			'verify',
			're-verify',
			'remove',
			'uninstall',
			'corrupt',
			'sha256',
			'checksum',
		],
	},
	{
		id: 'encore-a-cappella-self-test',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Voice self-test',
		description:
			'Load each speech runtime and run a trivial operation against it, reporting per-runtime pass/fail with timings plus the microphone permission. Loads no model and opens no microphone',
		keywords: [
			'self test',
			'selftest',
			'diagnostic',
			'voice not working',
			'microphone permission',
			'native runtime',
			'onnx',
			'llama',
			'whisper',
			'troubleshoot',
		],
	},
	{
		id: 'encore-a-cappella-run-self-test',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Run voice self-test',
		description:
			'Run the A Cappella runtime self-test now and show the per-runtime result, with a Copy button for pasting into a bug report',
		keywords: ['run self test', 'diagnose voice', 'voice broken', 'test microphone', 'debug voice'],
	},
	{
		id: 'encore-a-cappella-turn-latency',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Turn latency',
		description:
			'Where the last spoken turn spent its time, hop by hop, measured from the moment the detector heard you stop talking. Turns "voice feels slow" into a specific hop',
		keywords: [
			'latency',
			'turn latency',
			'slow',
			'timing',
			'timings',
			'performance',
			'first partial',
			'response time',
		],
	},
	{
		id: 'encore-a-cappella-read-turn-latency',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Read last turn',
		description:
			'Read the per-hop timings of the most recent spoken turn, with a Copy button for pasting into a bug report',
		keywords: ['read last turn', 'turn timings', 'voice slow', 'latency breakdown'],
	},
	{
		id: 'encore-a-cappella-voice-providers',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Voice Providers',
		description:
			'Which engine fills each voice slot, whether the pipeline is a cascade or the realtime tier, and where your audio goes for the configuration you picked',
		keywords: [
			'voice providers',
			'provider',
			'engine',
			'openai',
			'elevenlabs',
			'anthropic',
			'whisper',
			'kokoro',
			'qwen',
			'api key',
			'hosted',
			'local',
		],
	},
	{
		id: 'encore-a-cappella-audio-destination',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Where your audio goes',
		description:
			'A plain statement of whether audio stays on this machine or is sent to a service, worked out from the engines currently selected rather than written as copy',
		keywords: [
			'audio destination',
			'privacy',
			'where does my audio go',
			'stays on this machine',
			'sent to openai',
			'offline',
			'local only',
		],
	},
	{
		id: 'encore-a-cappella-pipeline',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Pipeline',
		description:
			'Cascade runs speech-to-text, routing, and speech separately and is the only shape a local install or an ElevenLabs voice can take. Realtime is lowest latency but speaks in the provider voice and sends audio to their servers',
		keywords: [
			'pipeline',
			'cascade',
			'realtime',
			'speech to speech',
			'latency',
			'low latency',
			'shape',
		],
	},
	{
		id: 'encore-a-cappella-provider-stt',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Speech-to-Text engine',
		description:
			'Which speech recognition engine runs: the mock, local Whisper, or hosted OpenAI. Its status comes from the capability gate, so a blocked session and this panel cannot disagree',
		keywords: ['stt engine', 'whisper', 'openai transcription', 'speech recognition', 'provider'],
	},
	{
		id: 'encore-a-cappella-provider-tts',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Text-to-Speech engine',
		description: 'Which speech synthesis engine runs: the mock, local Kokoro, or hosted ElevenLabs',
		keywords: ['tts engine', 'kokoro', 'elevenlabs', 'voice', 'synthesis', 'provider'],
	},
	{
		id: 'encore-a-cappella-provider-brain',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Conductor Brain engine',
		description:
			'Which model decides where a spoken instruction goes: the keyword mock, local Qwen3, hosted OpenAI, or hosted Anthropic',
		keywords: ['brain engine', 'qwen', 'openai', 'anthropic', 'claude', 'routing', 'provider'],
	},
	{
		id: 'encore-a-cappella-key-openai',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'OpenAI API key',
		description:
			'Stored in the OS keychain, never in settings.json and never in plain text on disk. Test checks it against OpenAI and tells a rate limit apart from a bad key',
		keywords: ['openai key', 'api key', 'credential', 'keychain', 'secret', 'token'],
	},
	{
		id: 'encore-a-cappella-key-elevenlabs',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'ElevenLabs API key',
		description:
			'Stored in the OS keychain, never in settings.json and never in plain text on disk. Test checks it against ElevenLabs',
		keywords: ['elevenlabs key', 'api key', 'credential', 'keychain', 'secret', 'voice key'],
	},
	{
		id: 'encore-a-cappella-key-anthropic',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Anthropic API key',
		description:
			'Stored in the OS keychain, never in settings.json and never in plain text on disk. Lets a user with a Claude key route without adding an OpenAI one',
		keywords: ['anthropic key', 'claude key', 'api key', 'credential', 'keychain', 'secret'],
	},
	{
		id: 'encore-a-cappella-voice-picker',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Voice',
		description:
			'Which voice replies are spoken in and how fast, with a Preview that speaks one fixed line so two voices can be compared on the same words',
		keywords: ['voice picker', 'voice', 'preview', 'speed', 'rate', 'faster', 'slower'],
	},
	{
		id: 'encore-a-cappella-reclaim-disk',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Reclaim disk',
		description:
			'Delete every A Cappella model. Offered when the feature is switched off so a feature you have stopped using does not keep gigabytes without saying so',
		keywords: ['reclaim', 'disk space', 'delete models', 'free space', 'cleanup', 'uninstall'],
	},
	{
		id: 'encore-plugins',
		tab: 'encore',
		tabLabel: 'Plugins',
		label: 'Plugins',
		description:
			'Community plugin subsystem (Alpha) - discover, enable, disable, install, and uninstall plugins. Foundation only: plugins are listed and managed but do not execute code yet',
		keywords: [
			'plugin',
			'plugins',
			'extension',
			'extend',
			'addon',
			'add-on',
			'community',
			'marketplace',
			'install',
			'uninstall',
			'alpha',
		],
	},
];
